# docker-compose.yml
version: '3'

services:

    migrate:
        build: .
        container_name: 'migrate'
        command: >
            /bin/sh -c "python3 manage.py makemigrations --force-color --no-input -v 3 && python3 manage.py makemigrations --merge --ni-input -v 3 && python3 createsuperuser --noinput; exit 0"
        environment:
            - DJANGO_SUPERUSER_USERNAME=admin
            - DJANGO_SUPERUSER_PASSWORD=admin
            - DJANGO_SUPERUSER_EMAIL=admin@example.com
        volumes:
            - .:/app

    gunicorn:
        image: hh-migrate
        container_name: 'gunicorn'
        restsrt: always
        command: /bin/sh -c "python3 -m gunicorn -b 0.0.0.0:80 hh.wsgi --reload"
        volumes: 
            - .:app
        ports:
            - 80:80
        depends_on:
            - migrate      


